# Sample Ansible Playbook1.yml
- 
    hosts: all #localhost
    connection: local # remove if you are using localhost without hosts file
    name: Play 1
    tasks:
        - name: Execute Date Command
          command: date
        - name: Execute java version check
          command: java -version
        - name: Execute ansible version check
          command: ansible --version
        - name: Execute docker version check
          command: docker --version
        - name: Test local action
          command: echo "Hello World"
        - name: Create new folder
          #This will create a new folder in your machine path
          #command: mkdir /Users/moxdroid/Documents/testAnsible
          command: mkdir $HOME/Desktop/devops-lab11

    
